version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
    depends_on:
      - db                 #Ensure db starts before app

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=todo_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
